### ISSUE TITLE
MSYS stat() doesn't set S_IFSOCK, breaking --reuse

### ISSUE THREAD

**Issue by cuviper** [cuviper/ssh-pageant#31] opened 2015-03-20 16:07 UTC
MSYS `stat()` always seems to set `S_IFREG` (regular file) for the socket path.  Also `fstat()` on a newly created `socket()` descriptor sets `S_IFCHR` instead.  Current Cygwin does set `S_IFSOCK` in both cases, even if the socket is dead.

The MSYS behavior is probably related to this old Cygwin bug: http://www.cygwin.com/ml/cygwin-patches/2002-q2/msg00481.html

As a result, the `--reuse` code which tries to clean up dead sockets will never succeed.  It has a safety measure to confirm that the path is a socket before removing it, and I'm not really keen to relax that.  At the moment though, I don't have any good ideas.

**Comment by pkiff** [comment] 2015-03-28 15:20
I have a possibly related symptom, but to be honest, I can't say for sure. 

On my Win7 64-bit system ssh-pageant sometimes seems to leave a .ssh-pageant-user file (where "user" is the name of the Windows user) in a [path-to-user-folder]\AppData\Local\Temp directory. I think this happens if I open an MSYS BASH shell, close it, and then open a new one. But it may happen in other circumstances - I do not always leave pageant running and do not start pageant on bootup. Regardless, once this file is there, BASH won't connect to ssh-pageant, and won't remove the file, so I get a connection error in my shell. If I manually delete that temp file, then the MSYS Bash shell will connect again just fine, and create a fresh copy of that temp file.

As with cuviper's experience, it does seem that whatever code governs reuse of an existing socket is not always working correctly for me.

**Comment by cuviper** [comment] 2015-03-28 21:49
I think my best suggestion for MSYS users right now is to just forget about `--reuse`, and drop `-a` along with it.  Just let each login shell start their own ssh-pageant, with implicit temporary paths, and put `ssh-pageant -k` in logout files to clean up.

It's really not a big deal to have a bunch of instances running -- they're much smaller in memory than each shell itself, take no cpu time except when actively queried, and the actual key storage is unified in Pageant anyway.

I need to add some examples back into the README of managing separate instances.  I do still think `--reuse` is a nice feature to have, but it's not always the best option.

**Comment by pkiff** [comment] 2015-03-30 17:57
That helps. And that works for me. Thanks.

**Comment by meffect** [comment] 2015-05-14 17:28
I think I have experienced this issue sporadically and it's hard to reproduce. 

I changed my .bashrc to

#eval $(/usr/bin/ssh-pageant -r -a "/tmp/.ssh-pageant")
eval $(/usr/bin/ssh-pageant "/tmp/.ssh-pageant")

And I get this error:

ssh-pageant: /tmp/.ssh-pageant: No such file or directory

So how am I supposed to get this to work, even if it means spawning multiple ssh-pageant.exe processes? -a + some randomly generated characters?

**Comment by cuviper** [comment] 2015-05-14 17:37
That path is the argument for `-a`.  If you just remove `-a`, then the path is left being interpreted as a command to run under ssh-pageant, which fails because the path doesn't event exist.

So remove that path too, and it will generate a random socket path for you.
`eval $(/usr/bin/ssh-pageant)`

**Comment by pkiff** [comment] 2015-05-14 17:40
FYI, on my Win7 x64 machine I've actually modified it to specify the exact hard-coded path, though I forget now if I actually needed this or if I had some other reason for doing it:
eval $(/C/Software/ssh-pageant/msys32/ssh-pageant)

**Comment by meffect** [comment] 2015-05-14 17:42
Ohh I see, that worked great. How do I kill the ssh-pageant.exe process after I close the terminal window? I'd want to kill the one specific to that terminal session right? And not kill all of them? A lot of times I have 10-20+ bash sessions open

**Comment by pkiff** [comment] 2015-05-14 17:46
On my system, if I properly close the BASH window using Exit, then the temp folder and its file remove themselves.

**Comment by cuviper** [comment] 2015-05-14 17:52
You can put `$(/usr/bin/ssh-pageant -k)` in your `$HOME/.bash_logout` (create if missing).  This will kill just that shell's instance, using SSH_PAGEANT_PID that the initial command puts in the environment.

You might also add `trap logout HUP` to your `.bashrc` to get the logout script to run in more cases, like if you close the terminal window directly.  (instead of exit/logout/CTRL-d in bash)

**Comment by meffect** [comment] 2015-05-14 17:55
@pkiff Windows 8.1, Cygwin x64 latest version. ConEmu latest version. I spawned 5 bash terminal sessions. Opening Cygwin minty with bash, and typing /exit did not remove the folder in /tmp and it did also not kill the windows ssh-pageant.exe process that spawned

**Comment by pkiff** [comment] 2015-05-14 17:58
Errp. See cuviper's comment above. Forgot that I'd already followed his advice earlier in this same thread to add the .bash_logout file!
https://github.com/cuviper/ssh-pageant/issues/31#issuecomment-87317145

**Comment by meffect** [comment] 2015-05-14 18:13
@cuviper The ```.bash_logout``` code worked really well. Still struggling a little bit with the ```trap logout HUP``` part. I added that specific code and it didn't do anything. So I googled and added this function to ```.bashrc``` : ```kill_pageant() { $(/usr/bin/ssh-pageant -k); }``` and then added this below it ```trap kill_pageant EXIT``` . That seems to work with Minty, but it's not working with ConEmu. 

I only use ConEmu currently so I'm going to keep researching to see if I can find a way to get it to work with ConEmu.

**Comment by cuviper** [comment] 2015-05-14 18:31
It all depends on how the window kills its shell process.  For mintty, it will send SIGHUP for a normal window close, or SIGKILL for shift-close.  There's no way to trap KILL, by design.

I'd guess ConEmu knows nothing about Cygwin signals, and it's probably using a winapi like `TerminateProcess`, which is quite like SIGKILL.

Force-killed processes also have no chance to clean up temp files, so such ssh-pageants will leave old `/tmp/ssh-*` directories around.  It's safe to just delete these.

**Comment by cuviper** [comment] 2015-05-14 18:45
BTW @meffect, I don't expect `--reuse` to have any issues on current Cygwin, only old MSYS.  My best guess for your intermittent issue is if you're starting several shells at once, then there may be a race condition.  For instance, ssh-pageants starting in two ConEmu tabs at once may both determine that an old path is dead, and both try to create a new one.

If that sounds like it may be your case, please open a new bug.  You could work around that by adding startup script that runs alone to launch ssh-pageant, so there's always an instance.

**Comment by meffect** [comment] 2015-05-14 20:20
Ahhh ok. Yes, let me see what I can do to recreate the issue. I do open 4 Consoles at once with this ```4 consoles.cmd```

    start C:\Travis\ConEmu\ConEmu64.exe -cmdlist ^
    C:\cygwin64\bin\bash -c "/bin/xhere /bin/bash.exe" -cur_console:fna:t:"Gulp1":C:"C:\cygwin64\Cygwin.ico" ^|^|^| ^
    C:\cygwin64\bin\bash -c "/bin/xhere /bin/bash.exe" -cur_console:s1TVna:t:"Gulp2":C:"C:\cygwin64\Cygwin.ico" ^|^|^| ^
    C:\cygwin64\bin\bash -c "/bin/xhere /bin/bash.exe" -cur_console:s1THna:t:"Task":C:"C:\cygwin64\Cygwin.ico" ^|^|^| ^
    C:\cygwin64\bin\bash -c "/bin/xhere /bin/bash.exe" -cur_console:s2THna:t:"Git":C:"C:\cygwin64\Cygwin.ico"

**Comment by cuviper** [comment] 2015-05-15 16:29
Yet another option is to change your startup to let the agent launch the shell, just `ssh-pageant bash`.  Then you don't need any cleanup in logout scripts -- it will just exit as soon as the shell exits.  This might even work better with ConEmu closes, but I'm not sure.

**Comment by meffect** [comment] 2015-06-01 23:47
It's hard to reproduce but what seems to be happening is: when i launch a bash shell, the ```eval $(/usr/bin/ssh-pageant -r -a "/tmp/.ssh-pageant")``` appears to not be reusing the existing ssh-pageant.exe process. I think it happens after a long period of time passes. Like a few hours maybe.

Then it instead spawns another ssh-pageant.exe process and then I start having issues.

Is there a possible reason why? Is the "/tmp/.ssh-pageant" file getting deleted somehow? (I should check next time I have the issue). Is there some reason why it wouldn't be able to recognize the existing ssh-pageant.exe process that is already running?

**Comment by cuviper** [comment] 2015-06-02 19:25
@meffect I'm not sure, but can you open a new issue with your findings?  We should discuss this separately since it's not the same MSYS S_IFSOCK problem.

**Closed** 2015-08-01 23:23 UTC
Labels: defect
