### ISSUE TITLE
OpenSSH 7.7 gives warning

### ISSUE THREAD

**Issue by ffes** [cuviper/ssh-pageant#55] opened 2018-04-16 07:58 UTC
Recently OpenSSH on Cygwin was upgraded to 7.7 and now ssh-pageant gives this warning when any ssh process is invoked.

```
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
```

This warning was added in OpenSSH 7.7:

https://www.openssh.com/txt/release-7.7

* ssh(1): Warn when the agent returns a ssh-rsa (SHA1) signature when
   a rsa-sha2-256/512 signature was requested. This condition is possible
   when an old or non-OpenSSH agent is in use. bz#279

Some examples:

```
$ git pull
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
Already up to date.
```

```
$ ssh frank@host.example.com
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
Welcome to Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-116-generic x86_64)
```

When I close pageant and use the native openssh keys the warning is not shown.

**Comment by cuviper** [comment] 2018-04-16 16:14
Thanks for the bug report, but I think this will have to be reported to Putty/Pageant itself.  `ssh-pageant` only acts as a middle-man between the UNIX socket and Windows messages, but doesn't interpret or examine the actual agent packets at all.

**Comment by cuviper** [comment] 2018-04-16 18:18
I can also reproduce this warning by connecting PuTTY to Fedora 28 (`openssh-7.7p1-2.fc28.x86_64`) with agent forwarding enabled, then `ssh localhost` within so that remote `ssh` talks to Pageant.

I'm closing this issue since `ssh-pageant` is not responsible for the content of the agent messages.

**Closed by cuviper** 2018-04-16 18:18 UTC

**Comment by cuviper** [comment] 2018-04-17 06:28
Even further, `ssh-agent` from `openssh-clients-7.4p1-16.el7.x86_64` triggers the same warning when forwarded to that F28 machine and the key is used.
